### ISSUE TITLE
Unable to install  in android

### ISSUE THREAD

**Issue by DevdattaShinde** [GastricSpark/ScrollDatePicker#2]
Hi,
I am trying implement this project in my build.gradle(module) file but its gives me "Error:(32, 13) Failed to resolve: com.github.gastricspark:scrolldatepicker:1.0.1" error while gradle build. 

Please help me how to use this...
Thanks in advance

**Comment by yousseftarek** [comment]
The problem here is a simple typo. The version is not 1.0.1 it's 0.0.1.
The dependency should be as follows:
compile 'com.github.gastricspark:scrolldatepicker:0.0.1'

**Comment by yousseftarek** [comment]
The problem here is a simple typo. The dependency version is not 1.0.1 it's 0.0.1 .
So the dependency should be as follows:
compile 'com.github.gastricspark:scrolldatepicker:0.0.1'

**Comment by MuralikrishnaGS** [comment]
Hi,
Can i please get to know the minimum SDK required?
does this library support below SDK 19?

Thanks in advance

**Comment by yousseftarek** [comment]
I think it doesn't support below SDK 19.
Looking through this build.gradle file you can tell:
https://github.com/GastricSpark/ScrollDatePicker/blob/master/library/build.gradle
Hope this helps
